### ISSUE TITLE
remove_role = role removed + throws error.

### ISSUE THREAD

**Issue by mvanio** [RolifyCommunity/rolify#200]
Same as a previous issue but without using squeel or postgres. The previous workaround of using a string for role name is not successful.

```
    >> u.remove_role "admin"
      Role Load (219.0ms)  SELECT "RM_ROLES".* FROM "RM_ROLES" INNER JOIN "RM_USERS_ROLES"         
    ON "RM_ROLES"."ID" = "RM_USERS_ROLES"."ROLE_ID" WHERE "RM_USERS_ROLES"."USER_ID" = 1 AND "RM_ROLES"."NAME" = 'admin'
       (225.0ms)  
    DELETE FROM "RM_USERS_ROLES" WHERE "RM_USERS_ROLES"."USER_ID" = 1 AND "RM_USERS_ROLES"."ROLE_ID" IN (10002)

    NoMethodError: undefined method `rm_users' for #<Role:0x6399e28>

        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activemodel-3.2.13/lib/active_model/attribute_methods.rb:407:in `method_missing'
from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/attribute_methods.rb:149:in `method_missing'
from C:/Ruby192/lib/ruby/gems/1.9.1/gems/rolify-3.2.0/lib/rolify/adapters/active_record/role_adapter.rb:26:in `block in remove'
from C:in `each'
from C:in `each'
from C:/Ruby192/lib/ruby/gems/1.9.1/gems/rolify-3.2.0/lib/rolify/adapters/active_record/role_adapter.rb:25:in `remove'
from C:/Ruby192/lib/ruby/gems/1.9.1/gems/rolify-3.2.0/lib/rolify/role.rb:55:in `remove_role'
from (irb):7
from C:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
from C:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
from C:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
from C:/Users/markv/Documents/pi/msbpi/script/rails:6:in `require'
from C:/Users/markv/Documents/pi/msbpi/script/rails:6:in `<top (required)>'
from -e:1:in `load'
from -e:1:in `<main>'
```

RM_USERS is the name of the users table.

**Comment by MaNikkel** [comment]
It is an old issue but had the same problem here.

Solved it by adding `config.remove_role_if_empty = false` in the Rolify initializer
