### ISSUE TITLE
PG::UndefinedColumn: ERROR:  column "user_id" does not exist

### ISSUE THREAD

**Issue by seoyoochan** [RolifyCommunity/rolify#347]
```
== 20150715052507 RolifyCreateRoles: migrating ================================
-- create_table(:roles)
   -> 0.0061s
-- create_table(:users_roles, {:id=>false})
   -> 0.0017s
-- add_index(:roles, :name)
   -> 0.0043s
-- add_index(:roles, [:name, :resource_type, :resource_id])
   -> 0.0042s
-- add_index(:users_roles, [:user_id, :role_id])
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "user_id" does not exist
: CREATE  INDEX  "index_users_roles_on_user_id_and_role_id" ON "users_roles"  ("user_id", "role_id")/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_index'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:661:in `block in method_missing'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:631:in `block in say_with_time'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:631:in `say_with_time'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:651:in `method_missing'
/Users/seoyoochan/dev/seoyoochan/db/migrate/20150715052507_rolify_create_roles.rb:17:in `change'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:605:in `exec_migration'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:588:in `block in migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:587:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:764:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:994:in `block in execute_migration_in_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:1040:in `block in ddl_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:1040:in `ddl_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:993:in `execute_migration_in_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:955:in `block in migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `each'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:819:in `up'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:797:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `eval'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `<main>'
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "user_id" does not exist
: CREATE  INDEX  "index_users_roles_on_user_id_and_role_id" ON "users_roles"  ("user_id", "role_id")
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_index'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:661:in `block in method_missing'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:631:in `block in say_with_time'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:631:in `say_with_time'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:651:in `method_missing'
/Users/seoyoochan/dev/seoyoochan/db/migrate/20150715052507_rolify_create_roles.rb:17:in `change'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:605:in `exec_migration'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:588:in `block in migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:587:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:764:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:994:in `block in execute_migration_in_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:1040:in `block in ddl_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:1040:in `ddl_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:993:in `execute_migration_in_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:955:in `block in migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `each'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:819:in `up'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:797:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `eval'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `<main>'
PG::UndefinedColumn: ERROR:  column "user_id" does not exist
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_index'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:661:in `block in method_missing'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:631:in `block in say_with_time'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:631:in `say_with_time'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:651:in `method_missing'
/Users/seoyoochan/dev/seoyoochan/db/migrate/20150715052507_rolify_create_roles.rb:17:in `change'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:605:in `exec_migration'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:588:in `block in migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:587:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:764:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:994:in `block in execute_migration_in_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:1040:in `block in ddl_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:1040:in `ddl_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:993:in `execute_migration_in_transaction'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:955:in `block in migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `each'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:819:in `up'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/migration.rb:797:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `eval'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

* In rolify_create_roles.rb *
`add_index(:users_roles, [ :user_id, :role_id ])` causes this error.

To fix this, delete that line and add the below directly by replacing with the delete line
```
    create_join_table :users, :roles do |t|
      t.index [:user_id, :role_id]
    end
```

or you can create a new migration for join tables as

```
class CreateJoinTableUserRole < ActiveRecord::Migration
  def change
    create_join_table :users, :roles do |t|
        t.index [:user_id, :role_id]
    end
  end
end
```

**Comment by wldcordeiro** [comment]
If you've found a fix to this issue, please create a pull request! Rolify is a community supported gem and welcomes contributors!

**Comment by scheals** [comment]
Ruby 2.2 has been EOL for nearly 5 years now - is this still an issue that you're looking into? I know that the README says 2.2+ is supported, so I guess this might be something that you're still interested in?

I imagine that this was the result of trying to set up Rolify, I did this in order:
```ruby
bin/rails g model user
bin/rails g rolify Role
bin/rails db:migrate
```
and encountered no errors. The line `add_index(:users_roles, [ :user_id, :role_id ])` is still present in the migration and seems to cause no issues, without the bit with a join table suggested as a fix in this issue.

WSL (Ubuntu 22.04), Ruby 3.1.2, Rails 7.0.4, PostgreSQL 14.6 using rbenv to manage Ruby versions.
