### ISSUE TITLE
Rails 4 engine: uninitialized constant Person (NameError) when using generator

### ISSUE THREAD

**Issue by vmcilwain** [RolifyCommunity/rolify#358]
Ruby: 2.2.2
Rails 4.2.4
Rolify 4.1.1

Hello, I am attempting to create an engine which needs to use a role system. I added rolify to my gemspec file; bundle installed and ran the generator.

I already have a person model but based on the instructions, it simply would just add code to that model and not overwrite anything else. Unfortunately, it seems to have an issue with the Person class and I am not sure how to resolve it.

Here is my output from the generator:

Jarvis:authenticatable vmcilwain [feature/rolify] $rails g rolify Role Person
      invoke  active_record
      create    app/models/authenticatable/role.rb
      invoke    rspec
      create      spec/models/authenticatable/role_spec.rb
      invoke      factory_girl
      create        spec/factories/authenticatable_roles.rb
/Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `const_get': uninitialized constant Person (NameError)
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `block in constantize'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `each'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `inject'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/rolify-4.1.1/lib/generators/active_record/rolify_generator.rb:59:in `model_content'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/rolify-4.1.1/lib/generators/active_record/rolify_generator.rb:25:in `inject_role_class'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/shell.rb:68:in `with_padding'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:133:in `_invoke_from_option_orm'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/rolify-4.1.1/lib/generators/rolify/rolify_generator.rb:17:in `start'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/generators.rb:157:in `invoke'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/engine/commands.rb:19:in `require'
	from /Users/vmcilwain/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/engine/commands.rb:19:in `<top (required)>'
	from bin/rails:12:in `require'
	from bin/rails:12:in `<main>'

**Comment by vmcilwain** [comment]
I created a test app and followed the initial set of instructions here:
https://github.com/RolifyCommunity/rolify/wiki/Devise---CanCanCan---rolify-Tutorial

I substituted User for Person and it didn't seem to have any issues loading. I can only assume this must be an issue related to me using this in a rails engine?

Though just for kicks, I did copy the code that was generated in the test app to the rails engine and I get:
`method_missing': undefined local variable or method `rolify' for #<Class:0x007fca46e64b60> (NameError)

Which is related to the rolify line at the top of my Person class.

The generator initially only generated role.rb and the rolify.rb. The role.rb file was empty but the rolify.rb initializer had content in it.

**Comment by NuckChorris** [comment]
Just ran into this myself, it's seemingly undocumented outside of the linked PR but `rails g rolify Role User engine` (note the `engine`) should work.  If you have Devise on that same model you also need to add `devise` to the end of the argument list like `rails g rolify Role User engine devise`

**Comment by wldcordeiro** [comment]
@NuckChorris Would you like to add this to the wiki? I'm not sure what can be done in Rolify to fix this but at least we can document the solution. @EppO Any ideas of solutions?

**Comment by kierr** [comment]
If the generator doesn't work for you in an existing setup, here is the simple line to add to your `user.rb`:

`rolify :role_cname => 'MyEngine::Role'`
