### ISSUE TITLE
exception when calling add_role

### ISSUE THREAD

**Issue by ewamarciniak** [RolifyCommunity/rolify#372]
I am experiencing errors when running tests where I call add_role method on the user. Here is the backtrace:
```
ActiveRecord::UnknownAttributeError:
       unknown attribute 'type' for User::HABTM_Roles.
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/attribute_assignment.rb:67:in `block in assign_attributes'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `each'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `assign_attributes'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/core.rb:281:in `initialize'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/inheritance.rb:61:in `new'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/inheritance.rb:61:in `new'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/reflection.rb:8:in `build_association'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/associations.rb:7:in `build_record'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/associations.rb:25:in `build'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/has_many_through_association.rb:95:in `build_through_record'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/has_many_through_association.rb:112:in `save_through_record'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/has_many_through_association.rb:66:in `insert_record'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:563:in `block (2 levels) in concat_records'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:408:in `replace_on_target'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:403:in `add_to_target'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:562:in `block in concat_records'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:560:in `each'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:560:in `concat_records'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/has_many_association.rb:180:in `concat_records'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/has_many_through_association.rb:44:in `concat_records'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:168:in `block in concat'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:182:in `transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:168:in `concat'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/has_many_through_association.rb:38:in `concat'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:540:in `replace_records'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:373:in `block in replace'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:182:in `transaction'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:373:in `replace'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:67:in `ids_writer'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/associations/builder/collection_association.rb:76:in `role_ids='
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/rolify-5.0.0/lib/rolify/adapters/active_record/role_adapter.rb:48:in `add'
     # /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/rolify-5.0.0/lib/rolify/role.rb:19:in `add_role'
     # ./spec/models/user_spec.rb:58:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `type=' for #<User::HABTM_Roles user_id: 12, role_id: nil>
     #   /Users/ewamarciniak/.rvm/gems/ruby-2.1.0/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:433:in `method_missing'
```
I have recently upgraded to the latest version of rolify.

Using rails version 4.2.5 which I have also upgraded to recently.

**Comment by lorefnon** [comment]
I have been unable to reproduce this with Rails 4.2.5, Postgres adapter and rolify master. Can you please provide a gist / github repo where the error can be easily reproduced. 

Also, are you using STI in either Role model or User model.
