### ISSUE TITLE
NoMethodError: undefined method `include?' for :role:Symbol

### ISSUE THREAD

**Issue by Meekohi** [RolifyCommunity/rolify#375]
Just removed Pundit and switched to Rolify. I had to temporarily remove `rolify` from the User model to get the migration to run. I put it back and added `resourcify` to the relevant models, but now I am getting this error when trying to add a basic role to a user.

Any ideas?

```
 > User.first.add_role :admin
  User Load (0.4ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  Role Load (0.5ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."name" = $1 AND "roles"."resource_type" IS NULL AND "roles"."resource_id" IS NULL  ORDER BY "roles"."id" ASC LIMIT 1  [["name", "admin"]]
NoMethodError: undefined method `include?' for :role:Symbol
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/rolify-5.0.0/lib/rolify/role.rb:17:in `add_role'
  from (irb):10
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  from /Users/meekohi/authtest/bin/rails:8:in `<top (required)>'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/spring-1.6.0/lib/spring/commands/rails.rb:6:in `call'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/spring-1.6.0/lib/spring/command_wrapper.rb:38:in `call'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/spring-1.6.0/lib/spring/application.rb:183:in `block in serve'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/spring-1.6.0/lib/spring/application.rb:156:in `fork'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/spring-1.6.0/lib/spring/application.rb:156:in `serve'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/spring-1.6.0/lib/spring/application.rb:131:in `block in run'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/spring-1.6.0/lib/spring/application.rb:125:in `loop'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/spring-1.6.0/lib/spring/application.rb:125:in `run'
  from /Users/meekohi/.rvm/gems/ruby-2.1.5@authtest/gems/spring-1.6.0/lib/spring/application/boot.rb:18:in `<top (required)>'
  from /Users/meekohi/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/meekohi/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from -e:1:in `<main>'2.1.5 :011 > 

```

**Comment by Meekohi** [comment]
This was in my User model and removing it seems to fix the issue... possibly leftover from Pundit. Just want to double check this is not something from Rolify right?
```
  def roles 
    return :role
  end
```

**Comment by wldcordeiro** [comment]
@Meekohi That isn't something from rolify.

**Comment by Meekohi** [comment]
Roger that. Thanks!
