### ISSUE TITLE
Master is red

### ISSUE THREAD

**Issue by PragTob** [RolifyCommunity/rolify#401]
Seems like master has been red for a month: https://travis-ci.org/RolifyCommunity/rolify/builds/123961090

Apparently some failure only for mongoid, maybe Travis pulled some new mongoid version? 

```
home/travis/.rvm/gems/ruby-2.3.0/gems/database_cleaner-1.5.2/lib/database_cleaner/mongoid/truncation.rb:31:in `session': undefined method `default_client' for Mongoid:Module (NoMethodError)

Did you mean?  default_session

	from /home/travis/.rvm/gems/ruby-2.3.0/gems/database_cleaner-1.5.2/lib/database_cleaner/moped/base.rb:29:in `db_version'

	from /home/travis/.rvm/gems/ruby-2.3.0/gems/database_cleaner-1.5.2/lib/database_cleaner/moped/truncation_base.rb:26:in `collections'

	from /home/travis/.rvm/gems/ruby-2.3.0/gems/database_cleaner-1.5.2/lib/database_cleaner/moped/truncation_base.rb:14:in `clean'

	from /home/travis/.rvm/gems/ruby-2.3.0/gems/database_cleaner-1.5.2/lib/database_cleaner/base.rb:92:in `clean'
```

example build: https://travis-ci.org/RolifyCommunity/rolify/jobs/123961101

**Comment by lorefnon** [comment]
Thanks for pointing this out. This has been fixed now.
