### ISSUE TITLE
Rails 5.2.0 error (Hash doesn't implement #arity)

### ISSUE THREAD

**Issue by crawfoal** [RolifyCommunity/rolify#487]
When I upgraded to Rails 5.2, I got this error:

```
/Users/amandacrawford/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/association.rb:51:in `build_scope': undefined method `arity' for #<Hash:0x00007f8e56c5fd28> (NoMethodError)
	from /Users/amandacrawford/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/association.rb:43:in `create_reflection'
	from /Users/amandacrawford/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/association.rb:31:in `build'
	from /Users/amandacrawford/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/associations.rb:1654:in `belongs_to'
	from /Users/amandacrawford/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/acts_as_paranoid-085b5cc6da14/lib/acts_as_paranoid/associations.rb:14:in `belongs_to_with_deleted'
	from /Users/amandacrawford/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/has_and_belongs_to_many.rb:67:in `add_left_association'
	from /Users/amandacrawford/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/has_and_belongs_to_many.rb:92:in `through_model'
	from /Users/amandacrawford/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.2.0/lib/active_record/associations.rb:1826:in `has_and_belongs_to_many'
	from /Users/amandacrawford/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rolify-5.2.0/lib/rolify.rb:30:in `rolify'
	from /Users/amandacrawford/Desktop/Code/greensteps/app/models/user.rb:3:in `<class:User>'
	from /Users/amandacrawford/Desktop/Code/greensteps/app/models/user.rb:1:in `<top (required)>'
```

**Comment by crawfoal** [comment]
Whoops, this is an issue with a different gem (acts_as_paranoid). Sorry about that!
