### ISSUE TITLE
Calling .count .one? or .many? on with_roles scope in Rails 7 raises StatementInvalid error

### ISSUE THREAD

**Issue by hidde-jan** [RolifyCommunity/rolify#584]
It seems rails 7 changed the way it performs counts.

Rails version: 7.0.3.1
Rolify version: 6.0.0

`.count` works in postgres, but raises in sqlite:

```
Event.with_roles(%i[admin manager], User.first).count
  Event Count (0.6ms)  SELECT COUNT("events".*) FROM "events" INNER JOIN "roles" ON "roles".resource_type IN ('Event') AND                                                                                                                 
                                    ("roles".resource_id IS NULL OR "roles".resource_id = "events"."id") WHERE ("roles".name IN ('admin','manager') AND "roles".resource_type IN ('Event')) AND ("roles"."id" IN (SELECT "roles"."id" FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = 1 AND "roles"."name" IN ('admin', 'manager')) AND (("roles".resource_id = "events"."id") OR ("roles".resource_id IS NULL)))            
/usr/local/bundle/gems/sqlite3-1.4.4/lib/sqlite3/database.rb:152:in `initialize': SQLite3::SQLException: near "*": syntax error (ActiveRecord::StatementInvalid)                                                                           
/usr/local/bundle/gems/sqlite3-1.4.4/lib/sqlite3/database.rb:152:in `initialize': near "*": syntax error (SQLite3::SQLException)     
```

`.one?` raises an invalid statement in both sqlite and postgres:

```
Event.with_roles(%i[admin manager], User.first).one?
D, [2022-09-11T08:16:30.877300 #503] DEBUG -- :   Event Count (1.9ms)  SELECT COUNT(count_column) FROM (SELECT "events".* AS count_column FROM "events" INNER JOIN "roles" ON "roles".resource_type IN ('Event') AND                                                                                                                 
                                    ("roles".resource_id IS NULL OR "roles".resource_id = "events"."id") WHERE ("roles".name IN ('admin','manager') AND "roles".resource_type IN ('Event')) AND ("roles"."id" IN (SELECT "roles"."id" FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = 1 AND "roles"."name" IN ('admin', 'manager')) AND (("roles".resource_id = "events"."id") OR ("roles".resource_id IS NULL))) LIMIT $1) subquery_for_count  [["LIMIT", 2]]
/opt/render/project/.gems/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PG::UndefinedColumn: ERROR:  column "count_column" does not exist (ActiveRecord::StatementInvalid)                                                                                  
LINE 1: SELECT COUNT(count_column) FROM (SELECT "events".* AS count_...                                                                      
                     ^                                                                                                                       
/opt/render/project/.gems/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': ERROR:  column "count_column" does not exist (PG::UndefinedColumn)                                                                                                                  
LINE 1: SELECT COUNT(count_column) FROM (SELECT "events".* AS count_... 
```

**Comment by patrickemuller** [comment]
@hidde-jan do you know if this is still happening?

**Comment by wheatevo** [comment]
I am seeing the same in latest Rails 7 (7.0.8) and Rolify 6.0.1.

Seems like https://github.com/RolifyCommunity/rolify/pull/580 is related to this issue.

**Comment by rstueven** [comment]
This may or may not be related, but either way...

Rails 7.1.3.2
Ruby 3.2.2
Rolify 6.0.1

Trying to get a list of all Users that have any role associated with a given Organization.

```
[21] pry(main)> User.with_roles([:cloud_user, :event_admin], Organization.find(76)).first
  Organization Load (4.7ms)  SELECT `organizations`.* FROM `organizations` WHERE `organizations`.`id` = 76 LIMIT 1
NoMethodError: undefined method `with_roles' for User:Class
from /Users/richard/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing'

[22] pry(main)> User.with_role([:cloud_user, :event_admin], Organization.find(76)).first
  Organization Load (1.9ms)  SELECT `organizations`.* FROM `organizations` WHERE `organizations`.`id` = 76 LIMIT 1
  User Load (1.3ms)  SELECT `users`.* FROM `users` INNER JOIN `users_roles` ON `users_roles`.`user_id` = `users`.`id` INNER JOIN `roles` ON `roles`.`id` = `users_roles`.`role_id` WHERE ((((roles.name = 'cloud_user','event_admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)) OR ((roles.name = 'cloud_user','event_admin') AND (roles.resource_type = 'Organization') AND (roles.resource_id IS NULL)) OR ((roles.name = 'cloud_user','event_admin') AND (roles.resource_type = 'Organization') AND (roles.resource_id = '76')))) ORDER BY `users`.`id` ASC LIMIT 1
ActiveRecord::StatementInvalid: Mysql2::Error: Operand should contain 1 column(s)
from /Users/richard/.rvm/gems/ruby-3.2.2/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
```

1. "undefined method `with_roles'" was unexpected.
2. The query is performing `=` instead of `IN()`:
`(roles.name = 'cloud_user','event_admin')`, thus generating the "Operand should contain 1 column(s)" error.

This works, but it's kinda ugly:
```
    User.where(id: UserRole.joins(:role)
                           .where(roles: { resource_type: 'Organization', resource_id: self.id })
                           .pluck(:user_id))
```
