### ISSUE TITLE
production error with dynamic shortcuts

### ISSUE THREAD

**Issue by m4tm4t** [RolifyCommunity/rolify#76]
production operations fail when migrating in production or assets compilation/clear with `config.use_dynamic_shortcuts` on postgresql

``` console

RAILS_ENV=production rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Invoke disable_rails_admin_initializer (first_time)
** Execute disable_rails_admin_initializer
** Execute environment
rake aborted!
PG::Error: ERROR:  relation "roles" does not exist
LINE 4:              WHERE a.attrelid = '"roles"'::regclass
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"roles"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:1139:in `async_exec'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:1139:in `exec_no_cache'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:663:in `block in exec_query'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:662:in `exec_query'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:1264:in `column_definitions'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:858:in `columns'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/model_schema.rb:228:in `yield'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/model_schema.rb:228:in `default'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/model_schema.rb:228:in `columns'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/model_schema.rb:237:in `columns_hash'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/locking/optimistic.rb:129:in `locking_enabled?'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/relation.rb:170:in `exec_queries'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/relation.rb:160:in `block in to_a'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/explain.rb:40:in `logging_query_plan'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/relation.rb:159:in `to_a'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/relation/finder_methods.rb:159:in `all'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/querying.rb:5:in `all'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/rolify-3.1.0/lib/rolify/dynamic.rb:4:in `load_dynamic_methods'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/rolify-3.1.0/lib/rolify.rb:25:in `rolify'
/home/foohey/dev/play/app/models/user.rb:3:in `<class:User>'
/home/foohey/dev/play/app/models/user.rb:1:in `<top (required)>'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `block in require'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:359:in `require_or_load'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:502:in `load_missing_constant'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:192:in `block in const_missing'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:190:in `each'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:190:in `const_missing'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/inflector/methods.rb:229:in `block in constantize'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/inflector/methods.rb:228:in `each'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/inflector/methods.rb:228:in `constantize'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:554:in `get'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:588:in `constantize'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise.rb:252:in `get'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise/mapping.rb:77:in `to'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise/mapping.rb:72:in `modules'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise/mapping.rb:89:in `routes'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise/mapping.rb:156:in `default_used_route'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise/mapping.rb:66:in `initialize'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise.rb:286:in `new'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise.rb:286:in `add_mapping'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise/rails/routes.rb:207:in `block in devise_for'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise/rails/routes.rb:206:in `each'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.0/lib/devise/rails/routes.rb:206:in `devise_for'
/home/foohey/dev/play/config/routes.rb:6:in `block in <top (required)>'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:282:in `instance_exec'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:282:in `eval_block'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:260:in `draw'
/home/foohey/dev/play/config/routes.rb:1:in `<top (required)>'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:245:in `load'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:245:in `block in load'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:245:in `load'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application/routes_reloader.rb:40:in `each'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/file_update_checker.rb:78:in `call'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/file_update_checker.rb:78:in `execute'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application/finisher.rb:66:in `block in <module:Finisher>'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/initializable.rb:30:in `run'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/initializable.rb:54:in `each'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application.rb:136:in `initialize!'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/foohey/dev/play/config/environment.rb:5:in `<top (required)>'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `block in require'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application.rb:103:in `require_environment!'
/home/foohey/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.3/lib/rails/application.rb:292:in `block (2 levels) in initialize_tasks'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/home/foohey/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/foohey/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `load'
/home/foohey/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `<main>'
Tasks: TOP => db:migrate => environment
```

**Comment by runar** [comment]
I would like to bump this, seeing that the note @EppO added to the initializer was removed by commit e5595f5, and that the original issue is not really solved. I had to «pause» Capistrano to manually edit the initializer on the server to disable the dynamic shortcuts.
